[build]
  command = "npm run build"
  publish = "dist"
  # functions = "./src/functions"

[context.production]
  environment = { NODE_VERSION = "10.15.3", NODE_ENV = "production" }

[dev]
  command = "npm run start"
  publish = "dist"
  port = 3000
  targetPort = 8181
  NODE_ENV = "development"
  # functionsPort = 34567

[[redirects]]
  from = "/post/*"
  to = "/blog/:splat"

[[headers]]
  for = "*.jpg"
  [headers.values]
    cache-control = "public, max-age=31557600, immutable"

[[headers]]
  for = "*.png"
  [headers.values]
    cache-control = "public, max-age=31557600, immutable"

[[headers]]
  for = "*.webp"
  [headers.values]
    cache-control = "public, max-age=31557600, immutable"

[[headers]]
  for = "*.avif"
  [headers.values]
    cache-control = "public, max-age=31557600, immutable"
    content-type = "image/avif"