[build]
  command = "npm run build"
  publish = "_site"

[context.production]
  environment = { NODE_VERSION = "16.15.0", NODE_ENV = "production" }

[dev]
  command = "npm run watch"
  publish = "_site"
  port = 3000
  NODE_ENV = "development"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31557600, immutable"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31557600, immutable"

[[headers]]
  for = "*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31557600, immutable"

[[headers]]
  for = "*.avif"
  [headers.values]
    Content-Type = "image/avif"
    Content-Disposition = "inline"
    Cache-Control = "public, max-age=31557600, immutable"